### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by thayes46** [gt-cs2110/cs2110docker#10]
For some non-native english speakers there are a few portions of the guide that are ambiguous or not obvious.

In section 4:
-  The pdf says to go to the url mentioned in the script, then isolated on the next line shows a non-functional address:
`http://<ip-address>:6901/vnc.html` . Either changing this to be the common case (127.0.0.1) or removing the example entirely would make this more clear to help students who don't understand that <> implies a changed value. Alternatively making the prompt in <> more clear would suffice.

- The phrasing surrounding how to ensure they can access files on the host machine is also targeted at the technical audience and a significant amount of students don't understand what the paragraph means. A step by step would be very useful for students

**Comment by kanwren** [comment]
I'm glad to hear the concerns! Most of this was written quite a while ago and the only updates since have been related to the new Windows installation.

Two questions:
- Do you have TAs that are willing to help out with improving/reviewing at some point? I can walk them through making a PR if so.
- Do you have a time frame for improvements to the document, or is it just before next semester?
